export interface PostgresDataTypes {
    bigint: "bigint";
    bigserial: "bigserial";
    bit: `bit`;
    bit_n: `bit (${number})`;
    bit_varying: `bit varying`;
    bit_varying_n: `bit varying (${number})`;
    boolean: "boolean";
    box: "box";
    bytea: "bytea";
    char: `char`;
    character: `character`;
    character_n: `character (${number})`;
    character_varying: `character varying`;
    character_varying_n: `character varying (${number})`;
    cidr: "cidr";
    // circle: "circle";
    date: "date";
    daterange: "daterange";
    double_precision: "double precision";
    inet: "inet";
    int2vector: "int2vector";
    int4range: "int4range";
    int8range: "int8range";
    integer: "integer";
    // interval: `interval`;
    json: "json";
    jsonb: "jsonb";
    line: "line";
    lseg: "lseg";
    macaddr: "macaddr";
    macaddr8: "macaddr8";
    money: "money";
    numeric: "numeric";
    numeric_p_s: `numeric (${number}, ${number})`;
    numrange: "numrange";
    oid: "oid";
    path: "path";
    pg_lsn: "pg_lsn";
    // point: "point";
    polygon: "polygon";
    real: "real";
    regclass: "regclass";
    regconfig: "regconfig";
    regdictionary: "regdictionary";
    regnamespace: "regnamespace";
    regoper: "regoper";
    regoperator: "regoperator";
    regproc: "regproc";
    regprocedure: "regprocedure";
    regrole: "regrole";
    regtype: "regtype";
    smallint: "smallint";
    smallserial: "smallserial";
    serial: "serial";
    text: "text";
    tid: "tid";
    time: "time";
    time_p: `time(${number})` | `time (${number})`;
    time_with_timezone: "time with time zone";
    time_without_timezone: "time without time zone";
    time_p_with_timezone: `time (${number}) with time zone`;
    time_p_without_timezone: `time (${number}) without time zone`;
    timetz: "timetz";
    timestamp: "timestamp";
    timestamp_p: `timestamp (${number})`;
    timestamp_with_timezone: "timestamp with time zone";
    timestamp_without_timezone: "timestamp without time zone";
    timestamp_p_with_timezone: `timestamp (${number}) with time zone`;
    timestamp_p_without_timezone: `timestamp (${number}) without time zone`;
    timestamptz: "timestamptz";
    tsquery: "tsquery";
    tsrange: "tsrange";
    tstzrange: "tstzrange";
    tsvector: "tsvector";
    txid_snapshot: "txid_snapshot";
    uuid: "uuid";
    varchar: "varchar";
    xid: "xid";
    xml: "xml";
}
