import {
    afterAll,
    beforeAll,
    beforeEach,
    describe,
    expect,
    test,
} from "vitest";

import { createTestDB } from "./util/db.js";

describe("all supported data types", () => {
    const { db, logger } = createTestDB();

    beforeEach(() => {
        logger.clear();
    });

    beforeAll(async () => {
        await db.connect();
    });

    afterAll(async () => {
        await db.close();
    });

    test("can insert and retrieve all field types", async () => {
        await db.transact(
            async (db) => {
                const created = await db.createOne("kitchenSink", {
                    values: {
                        charField: "a",
                        characterField: "b",
                        characterNField: "abc",
                        varcharField: "def",
                        varcharNField: "ghi",
                        textField: "hello world",
                        bitField: "1",
                        bitNField: "101",
                        bitVaryingField: "101",
                        bitVaryingNField: "101",
                        numericField: "123",
                        numericPrecisionField: "123.45",
                        integerField: 42,
                        bigintField: 9007199254740991n,
                        smallintField: 32767,
                        doublePrecisionField: 3.14159,
                        realField: 3.14,
                        moneyField: "19.99",
                        booleanField: true,
                        uuidField: "123e4567-e89b-12d3-a456-426614174000",
                        dateField: new Date("2023-01-01"),
                        timeField: "13:45:30",
                        timeWithPrecisionField: "13:45:30",
                        timetzField: "13:45:30+00",
                        timeWithTzField: "13:45:30+00",
                        timestampField: new Date("2023-01-01T13:45:30"),
                        timestampWithPrecisionField: new Date(
                            "2023-01-01T13:45:30",
                        ),
                        timestamptzField: new Date("2023-01-01T13:45:30Z"),
                        timestampWithTzField: new Date("2023-01-01T13:45:30Z"),
                        // intervalField: { years: 1, months: 2 },
                        jsonField: { key: "value" },
                        jsonbField: { key: "value" },
                        // pointField: { x: 1, y: 2 },
                        lineField: "{1,2,3}",
                        lsegField: "[(1,2),(3,4)]",
                        boxField: "(3,4),(1,2)",
                        polygonField: "((1,2),(3,4),(5,6))",
                        // circleField: { x: 1, y: 2, radius: 3 },
                        cidrField: "192.168.100.128/25",
                        inetField: "192.168.100.128",
                        macaddrField: "08:00:2b:01:02:03",
                        macaddr8Field: "08:00:2b:01:02:03:04:05",
                        byteaField: Buffer.from("hello"),
                        xmlField: "<root>test</root>",
                        pathField: "((1,2),(3,4),(5,6))",
                        tsqueryField: "'fat' & 'rat'",
                        tsvectorField: "'a' 'cat' 'fat' 'mat' 'on' 'sat'",
                        int4rangeField: "[1,4)",
                        int8rangeField: "[1,9223372036854775807)",
                        numrangeField: "[1.123,4.456)",
                        tsrangeField: `["2023-01-01 00:00:00","2023-01-02 00:00:00")`,
                        tstzrangeField: `["2023-01-01 00:00:00+00","2023-01-02 00:00:00+00")`,
                        daterangeField: "[2023-01-01,2023-01-02)",
                        int2vectorField: "1 2 3",
                        oidField: 1234,
                        pglsnField: "0/1234567",
                        regclassField: "pg_class",
                        regnamespaceField: "pg_catalog",
                        regprocField: "now",
                        regprocedureField: "sum(integer)",
                        regroleField: "orm",
                        regtypeField: "integer",
                        tidField: "(0,1)",
                        xidField: "1234",
                        txidSnapshotField: "10:20:10,14,15",
                        arrayField: ["a", "b", "c"],
                        multiArrayField: [
                            [
                                ["a", "b"],
                                ["c", "d"],
                            ],
                            [
                                ["e", "f"],
                                ["g", "h"],
                            ],
                        ],
                    },
                    returning: [
                        "charField",
                        "characterField",
                        "characterNField",
                        "varcharField",
                        "varcharNField",
                        "textField",
                        "bitField",
                        "bitNField",
                        "bitVaryingField",
                        "bitVaryingNField",
                        "numericField",
                        "numericPrecisionField",
                        "integerField",
                        "bigintField",
                        "smallintField",
                        "serialField",
                        "bigserialField",
                        "smallserialField",
                        "doublePrecisionField",
                        "realField",
                        "moneyField",
                        "booleanField",
                        "uuidField",
                        "dateField",
                        "timeField",
                        "timeWithPrecisionField",
                        "timetzField",
                        "timeWithTzField",
                        "timestampField",
                        "timestampWithPrecisionField",
                        "timestamptzField",
                        "timestampWithTzField",
                        "jsonField",
                        "jsonbField",
                        "lineField",
                        "lsegField",
                        "boxField",
                        "polygonField",
                        "cidrField",
                        "inetField",
                        "macaddrField",
                        "macaddr8Field",
                        "byteaField",
                        "xmlField",
                        "pathField",
                        "tsqueryField",
                        "tsvectorField",
                        "int4rangeField",
                        "int8rangeField",
                        "numrangeField",
                        "tsrangeField",
                        "tstzrangeField",
                        "daterangeField",
                        "int2vectorField",
                        "oidField",
                        "pglsnField",
                        "regclassField",
                        "regnamespaceField",
                        "regprocField",
                        "regprocedureField",
                        "regroleField",
                        "regtypeField",
                        "tidField",
                        "xidField",
                        "txidSnapshotField",
                        "arrayField",
                        "multiArrayField",
                    ],
                });

                const retrieved = await db.findOne("kitchenSink", {
                    select: [
                        "charField",
                        "characterField",
                        "characterNField",
                        "varcharField",
                        "varcharNField",
                        "textField",
                        "bitField",
                        "bitNField",
                        "bitVaryingField",
                        "bitVaryingNField",
                        "numericField",
                        "numericPrecisionField",
                        "integerField",
                        "bigintField",
                        "smallintField",
                        "serialField",
                        "bigserialField",
                        "smallserialField",
                        "doublePrecisionField",
                        "realField",
                        "moneyField",
                        "booleanField",
                        "uuidField",
                        "dateField",
                        "timeField",
                        "timeWithPrecisionField",
                        "timetzField",
                        "timeWithTzField",
                        "timestampField",
                        "timestampWithPrecisionField",
                        "timestamptzField",
                        "timestampWithTzField",
                        "jsonField",
                        "jsonbField",
                        "lineField",
                        "lsegField",
                        "boxField",
                        "polygonField",
                        "cidrField",
                        "inetField",
                        "macaddrField",
                        "macaddr8Field",
                        "byteaField",
                        "xmlField",
                        "pathField",
                        "tsqueryField",
                        "tsvectorField",
                        "int4rangeField",
                        "int8rangeField",
                        "numrangeField",
                        "tsrangeField",
                        "tstzrangeField",
                        "daterangeField",
                        "int2vectorField",
                        "oidField",
                        "pglsnField",
                        "regclassField",
                        "regnamespaceField",
                        "regprocField",
                        "regprocedureField",
                        "regroleField",
                        "regtypeField",
                        "tidField",
                        "xidField",
                        "txidSnapshotField",
                        "arrayField",
                        "multiArrayField",
                    ],
                });

                expect(retrieved).toEqual(created);
            },
            { rollback: true },
        );
    });
});
