import { ModelDefinition } from "@casekit/orm-schema";

export const kitchenSink = {
    fields: {
        id: { type: "serial", primaryKey: true },
        charField: { type: "char" },
        characterField: { type: "character" },
        characterNField: { type: "character(24)" },
        varcharField: { type: "character varying" },
        varcharNField: { type: "character varying(24)" },
        textField: { type: "text" },
        bitField: { type: "bit" },
        bitNField: { type: "bit(3)" },
        bitVaryingField: { type: "bit varying" },
        bitVaryingNField: { type: "bit varying(3)" },
        numericField: { type: "numeric" },
        numericPrecisionField: { type: "numeric(5,2)" },
        integerField: { type: "integer" },
        bigintField: { type: "bigint" },
        smallintField: { type: "smallint" },
        serialField: { type: "serial" },
        bigserialField: { type: "bigserial" },
        smallserialField: { type: "smallserial" },
        doublePrecisionField: { type: "double precision" },
        realField: { type: "real" },
        moneyField: { type: "money" },
        booleanField: { type: "boolean" },
        uuidField: { type: "uuid" },
        dateField: { type: "date" },
        timeField: { type: "time" },
        timeWithPrecisionField: { type: "time(3)" },
        timetzField: { type: "timetz" },
        timeWithTzField: { type: "time with time zone" },
        timestampField: { type: "timestamp" },
        timestampWithPrecisionField: { type: "timestamp(6)" },
        timestamptzField: { type: "timestamptz" },
        timestampWithTzField: { type: "timestamp with time zone" },
        // intervalField: { type: "interval" },
        jsonField: { type: "json" },
        jsonbField: { type: "jsonb" },
        // pointField: { type: "point" },
        lineField: { type: "line" },
        lsegField: { type: "lseg" },
        boxField: { type: "box" },
        polygonField: { type: "polygon" },
        // circleField: { type: "circle" },
        cidrField: { type: "cidr" },
        inetField: { type: "inet" },
        macaddrField: { type: "macaddr" },
        macaddr8Field: { type: "macaddr8" },
        byteaField: { type: "bytea" },
        xmlField: { type: "xml" },
        pathField: { type: "path" },
        tsqueryField: { type: "tsquery" },
        tsvectorField: { type: "tsvector" },
        int4rangeField: { type: "int4range" },
        int8rangeField: { type: "int8range" },
        numrangeField: { type: "numrange" },
        tsrangeField: { type: "tsrange" },
        tstzrangeField: { type: "tstzrange" },
        daterangeField: { type: "daterange" },
        int2vectorField: { type: "int2vector" },
        oidField: { type: "oid" },
        pglsnField: { type: "pg_lsn" },
        regclassField: { type: "regclass" },
        regnamespaceField: { type: "regnamespace" },
        regprocField: { type: "regproc" },
        regprocedureField: { type: "regprocedure" },
        regroleField: { type: "regrole" },
        regtypeField: { type: "regtype" },
        tidField: { type: "tid" },
        xidField: { type: "xid" },
        txidSnapshotField: { type: "txid_snapshot" },
        arrayField: { type: "text[]" },
        multiArrayField: { type: "text[][][]" },
    },
} as const satisfies ModelDefinition;
